### ISSUE TITLE
课表无法导入，在正常登录的情况下显示已导入的课表为空。

### ISSUE THREAD

**Issue by lizhiyuaner** [flylai/GlutAssistant#1]

**Comment by flylai** [comment]
@lizhiyuaner 请问是哪个校区，哪个版本，哪届的学生呢

**Comment by lizhiyuaner** [comment]
雁山校区2020届
版本1.5.4，应该是最新版

**Comment by flylai** [comment]
请问方便
1.先在这里登录教务
[http://jw.glut.edu.cn/academic/common/security/login.jsp](http://jw.glut.edu.cn/academic/common/security/login.jsp)
2.然后去这里
[http://jw.glut.edu.cn/academic/student/currcourse/currcourse.jsdo?groupId=&moduleId=2000&randomString=20201017175200ZOdL3Y](http://jw.glut.edu.cn/academic/student/currcourse/currcourse.jsdo?groupId=&moduleId=2000&randomString=20201017175200ZOdL3Y)
把课程列表截图一下吗

**Comment by lizhiyuaner** [comment]
好的
![1](https://user-images.githubusercontent.com/72716566/96357011-75f0a000-1128-11eb-9ee0-e34a45087d6e.PNG)

**Comment by flylai** [comment]
看起来并没有什么问题，请确认学年和学期是否选择正确
如正确
是否可以在课程列表右键，将网页另存为，把网页压缩为zip或者更改扩展名为txt上传呢，以便我在开发环境下做下测试

**Comment by lizhiyuaner** [comment]
[本学期课程安排.zip](https://github.com/flylai/GlutAssistant/files/5396992/default.zip)
![错误截图](https://user-images.githubusercontent.com/72716566/96357427-27de9b00-112e-11eb-98c1-77111dff2362.jpg)
选择是正确的，附错误截图和原网页

**Comment by flylai** [comment]
抱歉，由于Chrome等浏览器保存网页会将网页的部分代码进行更改，我没有实现预料到
可否右键查看网页源码，然后将其复制到txt中再次上传呢。

**Comment by flylai** [comment]
你试试这个文件，下载下来之后改扩展名为apk，安装即可
[app-armeabi-v7a-release.zip](https://github.com/flylai/GlutAssistant/files/5397514/app-armeabi-v7a-release.zip)

**Comment by lizhiyuaner** [comment]
[本学期课程安排.txt](https://github.com/flylai/GlutAssistant/files/5397625/default.txt)
抱歉回复晚了，但您所提供的软件在我所持有的所有Android设备上均无法正常运行（表现为打开后直接闪退，或打开后白屏）
还是附上网页源码，希望能有所帮助。

**Comment by flylai** [comment]
试试这个呢
下载下来之后改扩展名为apk，安装即可
[app-release.zip](https://github.com/flylai/GlutAssistant/files/5399383/app-release.zip)

**Comment by lizhiyuaner** [comment]
解决了，谢谢

**Comment by flylai** [comment]
非常感谢您提出bug，晚些时候再发布新版本
